import asyncio, os
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path="/opt/pw-browsers/chromium-1194/chrome-linux/chrome")
        pg = await b.new_page(viewport={"width":390,"height":844}, device_scale_factor=2)
        errs=[]; pg.on("pageerror", lambda e: errs.append(str(e))); pg.on("console", lambda m: m.type=="error" and errs.append(m.text))
        await pg.goto("http://localhost:8765/index.html"); await pg.wait_for_timeout(1500)
        await pg.click("text=Create a character"); await pg.wait_for_timeout(500)
        await pg.click("[data-tab=gear]"); await pg.wait_for_timeout(300)
        await pg.screenshot(path="test/gear-empty.png", full_page=True)
        await pg.select_option("[data-card=armor] select", "Chain Mail")
        await pg.click("text=No shield")
        await pg.select_option("[data-card=weapons] select", "Longsword")
        await pg.click("[data-card=weapons] button:has-text('Add')")
        await pg.click("text=Magic items")
        await pg.fill("[data-card=items] input", "ring of prot")
        await pg.click("[data-card=items] .skrow button")
        await pg.click("[data-card=items] summary")
        await pg.click("text=Not attuned")
        await pg.fill("[data-card=coins] input >> nth=1", "150")
        await pg.wait_for_timeout(300)
        ac = await pg.inner_text(".stat .v >> nth=0")
        await pg.screenshot(path="test/gear-full.png", full_page=True)
        await pg.click("[data-tab=play]"); await pg.wait_for_timeout(300)
        await pg.screenshot(path="test/sheet.png")
        print("AC on gear tab:", ac); print("errors:", errs)
        await b.close()
asyncio.run(main())
